AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Create pipeline-dashboard application.'
Resources:
  PipelineDashboardEventHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Create CloudWatch metrics from CodePipeline events
      Handler: index.handlePipelineEvent
      Runtime: nodejs6.10
      CodeUri: s3://meow-meow-meow-ray-us-east-1/df9df41fcba07b5e5827f6474128c22f
      Events:
        PipelineEventRule:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.codepipeline"
              detail-type:
                - "CodePipeline Pipeline Execution State Change"
                - "CodePipeline Stage Execution State Change"
                - "CodePipeline Action Execution State Change"
      Policies:
      - CloudWatchPutMetricPolicy: {}
#      - Version: '2012-10-17'
#        Statement:
#        - Effect: Allow
#          Resource: '*'
#          Action:
#          - codepipeline:ListPipelineExecutions
  PipelineDashboardGenerator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Build CloudWatch dashboard from CloudWatch metrics
      Handler: index.generateDashboard
      Runtime: nodejs6.10
      CodeUri: s3://meow-meow-meow-ray-us-east-1/df9df41fcba07b5e5827f6474128c22f
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: "cron(*/5 * * * ? *)"
      Policies:
#      - Version: '2012-10-17'
#        Statement:
#        - Effect: Allow
#          Resource: '*'
#          Action:
#          - cloudwatch:ListMetrics
#          - cloudwatch:GetDashboard
#          - cloudwatch:PutDashboard
